### ISSUE TITLE
Does not return anything

### ISSUE THREAD

**Issue by goooroooX** [anilyuk/punydomaincheck#2]
Hi,

I've tried this script with several domains (including malicious), with and without virusltotal key, but result is always the same: nothing.
On second run with virustotal key it throws massive 'too many calls' exceptions and hangs.
[Partly internationalized](https://www.networkworld.com/article/3191535/security/phishing-attacks-using-internationalized-domains-are-hard-to-block.html) domains are not supported - script return KeyError exception.

Is there any working scenario?
Thanks.

**Comment by anilyuk** [comment]
Can you give details ? Command output, domain names you tried etc.

**Comment by anilyuk** [comment]
I think I found the problem of key error. Tool is using freegeoip.net API service, but they shut down free service. I am going to update it to use different geolocation service but now you can use it without geolocation support. 

Also we are going to add support for partly internationalized domains, thank you for warning us!
