### ISSUE TITLE
No return in CLI

### ISSUE THREAD

**Issue by MamrK29** [anilyuk/punydomaincheck#3]
Hi There,

When I run Punydomaincheck on the CLI there is nothing returned (see screenshot), I saw another open issue and was wondering if this is the same problem as that one. It says that the geolocation tool is no longer available, what is the process of changing to a different tool?

![punycheck](https://user-images.githubusercontent.com/11075698/61669094-d5090000-acac-11e9-9182-2a8fdbfe4aaa.JPG)

**Comment by anilyuk** [comment]
Hi!

I tried with same parameters but there wasn't any problem with the tool. There wasn't punyencoded alternative for that domain, lucky for you :)
Also I am going to release new version with geolocation support.

Regards

**Comment by MamrK29** [comment]
Hey!

Thanks for the reply. I meant to comment on this yesterday, looked through the code base and it realized that the tool was functioning as intended. Looking forward to the new release. 

Also, I tried to run it with the original domain and zero punyencoded characters and it was not pulling to whois information or the virustotal scan report, have there been other cases of this as an issue?

Thanks

**Comment by anilyuk** [comment]
Hi!
I updated tool to correctly run Virustotal queries, added Geolocation support back again.

Whois is working correctly but some whois responses doesn't have "Contact" information. So it is normal to see empty fields.
